name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs mkdocs-material mkdocs-material-extensions
      - run: mkdocs gh-deploy --force --clean --remote-branch gh-pages
